language: python
python:
        - '3.5'

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings.travis"

before_script:
        - pip install -r requirements.txt

branches:
        only:
                - ContinuousIntegration

services:
        - postgresql

script:
        - cd pur_beurre
        - ./manage.py test
