# Generated by Django 2.0.3 on 2018-04-11 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('categories', models.CharField(max_length=500)),
                ('score', models.CharField(max_length=5)),
                ('code', models.IntegerField(unique=True)),
            ],
        ),
    ]
