# Generated by Django 2.0.3 on 2018-04-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute', '0004_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_small_url',
            field=models.URLField(default='no_url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='nutriments',
            field=models.CharField(default='no_nutriments_informations', max_length=1500),
            preserve_default=False,
        ),
    ]
